micronaut:
  application:
    name: sample-micronaut
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: false

test.property: hello
greeting:
  template: "Hola, %s!"
